# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WKWebViewLearn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WKWebViewLearn

  target 'WKWebViewLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKWebViewLearnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
